/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_co_uniquantum_search_SearchModule */

#ifndef _Included_kr_co_uniquantum_search_SearchModule
#define _Included_kr_co_uniquantum_search_SearchModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    InitModule
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_uniquantum_search_SearchModule_InitModule
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    ExitModule
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_co_uniquantum_search_SearchModule_ExitModule
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSidoCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSidoCount
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetSidoData
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetSidoData
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSidoName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSidoName
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSidoNameByDCode
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSidoNameByDCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSigunguCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSigunguCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSigunguName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSigunguName
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSigunguNameByDCode
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSigunguNameByDCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetSigunguData
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetSigunguData
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetDongCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetDongCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSearchDongCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSearchDongCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetDongName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetDongName
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetDongNameByDCode
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetDongNameByDCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetDongData
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetDongData
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetBunjiCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetBunjiCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetBunjiValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetBunjiValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetHoCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetHoCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetHoValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetHoValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetHoData
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetHoData
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetRoadCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetRoadCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSearchRoadCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSearchRoadCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetRoadName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetRoadName
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetRoadData
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetRoadData
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetRoadBunjiCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetRoadBunjiCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetRoadBunjiValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetRoadBunjiValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetRoadHoCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetRoadHoCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetRoadHoValue
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetRoadHoValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetRoadHoData
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetRoadHoData
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetAptCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetAptCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetCatePoiCount
 * Signature: (Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetCatePoiCount
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSearchPoiNameCount
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSearchPoiNameCount
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetSearchPoiCallCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kr_co_uniquantum_search_SearchModule_GetSearchPoiCallCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    MoveFirstPoiData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_uniquantum_search_SearchModule_MoveFirstPoiData
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    MoveNextPoiData
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_uniquantum_search_SearchModule_MoveNextPoiData
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    IsCatePoi
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_uniquantum_search_SearchModule_IsCatePoi__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    IsCatePoi
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_kr_co_uniquantum_search_SearchModule_IsCatePoi__
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetPoiName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetPoiName__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetPoiName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetPoiName__
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetPoiBranchName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetPoiBranchName__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetPoiBranchName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetPoiBranchName__
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetPoiCallNumber
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetPoiCallNumber__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    GetPoiCallNumber
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_co_uniquantum_search_SearchModule_GetPoiCallNumber__
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetPoiData
 * Signature: (I)[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetPoiData__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_GetPoiData
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1GetPoiData__
  (JNIEnv *, jobject);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    SetLocationPos
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_kr_co_uniquantum_search_SearchModule_SetLocationPos
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     kr_co_uniquantum_search_SearchModule
 * Method:    JNI_ChangedLocationCode
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_kr_co_uniquantum_search_SearchModule_JNI_1ChangedLocationCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
